# Generated by Django 4.1 on 2022-09-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Rule Name')),
                ('permission', models.CharField(choices=[('N', 'No Access'), ('F', 'Full Accsess'), ('M', 'Modify access'), ('RX', 'Read and execute access'), ('R', 'Read-only access'), ('W', 'Write-only access')], default='F', max_length=50)),
                ('accsess', models.CharField(choices=[('grant', 'grant'), ('deny', 'deny'), ('remove', 'remove'), ('setintegritylevel', 'setintegritylevel')], default='grant', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Policy Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('logs', models.ManyToManyField(blank=True, related_name='policy_logs', to='dlp.logs')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dlp.rule')),
            ],
        ),
    ]
